# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
    
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10","3.11"]
        
    runs-on: ${{matrix.runner}}

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 
      uses: actions/setup-python@v3
      with:
        python-version: ${{matrix.python-version}}
        
    - name: Install dependencies
      run: |
        python -m setup install    
        
    - name: Python version
      run: |
        python -V
  
    - name: Run Tests
      run: |
        python -m unittest
